### ISSUE TITLE
The CAYO Primary and Secondary Target Values have Since Changed

### ISSUE THREAD

**Issue by PROWLER2K21** [MichalD96/Perico-heist-goods-counter#14]
Panther------------------UNCHANGED
Sinsimito Tequila..............$630,000
Ruby Necklace.................$700.000
Bearer Bonds...................$770,000
Safe Cash.........................$20.000 - $99.000

Setup Fee.........................$100 000

Cash...........................$78,750 - $83,250
Artwork......................$157.500 - $180.000
Weed..........................$130.500 - $135.000
Cocaine......................$198.000 - $202.500
Gold...........................$328,333 - $333.333 (UNCHANGED)

**Comment by PROWLER2K21** [comment]
![Cayo Targets](https://github.com/MichalD96/Perico-heist-goods-counter/assets/150628818/886512b9-76fe-469e-a6d6-adf053c488af)

**Comment by MichalD96** [comment]
I updated the values immediately after the game update. What is wrong with my calculator?

**Comment by PROWLER2K21** [comment]
![image](https://github.com/MichalD96/Perico-heist-goods-counter/assets/150628818/0033da07-95e7-4bfa-a1d0-5d6ede538e08)

**Comment by PROWLER2K21** [comment]
It shows old payout values and if you look at the primary targets its not that high anymore. I mean i have Panther and Pink Diamond so I dont really care, but it helps me to explain to others the value of their heist. For some reason, yours is calculating at 1.6 million where they willnever get it that with the primary of Bearer Bonds anymore

**Comment by MichalD96** [comment]
On the screenshot you set tequila ($630,000 in standard mode) + 3 bags of gold which is 3x $400,000.
If we sum that, it is $1,830,000. Subtract from that fencing fee, Pavel fee, and you will get $1,540,00 for all 3 players.
I have no idea which part is wrong in your opinion, i play Cayo with friends daily, and the highest difference i ever noticed was about $10k

**Comment by PROWLER2K21** [comment]
Test it out, run one and test it out cause the calculations off since the change. I loved this prior to the changes…

**Comment by MichalD96** [comment]
I still don't understand what is wrong...
Show your calculations

**Comment by Your-Paramour** [comment]
How come the secondary values are different for the different primary values?

**Comment by MichalD96** [comment]
@Your-Paramour There was a cayo nerf, that introduced 3 hours cooldown for players that completed the heist alone. In the same update R* added 72 hours bonus for secondary targets. If you restart the heist within that 72 hours real time your secondary targets will be worth a bit more.
If you got panther/pink diamond, your secondary targets value don't change.
If you got Bearer bonds secondary targets are worth 5% more, ruby necklace 10% more, and tequila 20% more.

**Comment by Your-Paramour** [comment]
> @Your-Paramour There was a cayo nerf, that introduced 3 hours cooldown for players that completed the heist alone. In the same update R* added 72 hours bonus for secondary targets. If you restart the heist within that 72 hours real time your secondary targets will be worth a bit more. If you got panther/pink diamond, your secondary targets value don't change. If you got Bearer bonds secondary targets are worth 5% more, ruby necklace 10% more, and tequila 20% more.

Ah I had no idea the secondary targets were more valuable with the less good primary targets. So there's really no value in the better primary targets outside of of the pink diamond and panther it seems.

**Comment by PROWLER2K21** [comment]
I was trying to begin that explanation but after you resented and defended, I stopped and yielded. In many circumstances the primary is the only thing that matters.

I have tested every primary from panther to tequila, the game algorithms automatically compensate for certain conditions.

In addition, if you have hard mode and go in and get detected, when you restart, the safe will automatically give you between 60k-99k. I was amazed to find RS able to fix something like that but not other broken parts of the game. But I digress, the important thing is that you are now aware.

**Comment by MichalD96** [comment]
@PROWLER2K21 I have never said, that primary target is the only thing that matters. I asked what is wrong, and you posted screenshot without any context. Saying that "It's wrong" didn't give me any clue what is wrong in your opinion. Calculator has complicated logic, and sometimes errors happens, but i couldn't find anything abnormal on your screenshot.
@Your-Paramour asked precise question, and i was able go give precise answer.

**Comment by MichalD96** [comment]
> I was trying to begin that explanation but after you resented and defended, I stopped and yielded. In many circumstances the primary is the only thing that matters.
> 
> I have tested every primary from panther to tequila, the game algorithms automatically compensate for certain conditions.
> 
> In addition, if you have hard mode and go in and get detected, when you restart, the safe will automatically give you between 60k-99k. I was amazed to find RS able to fix something like that but not other broken parts of the game. But I digress, the important thing is that you are now aware.

Yes, If you restart heist within 72 hours, the best target is panther/pink diamond, then tequila, ruby necklace and the worst are bearer bonds.
This is caused by mentioned earlier bonus, additional 20% value of secondary targets is worth more than value of difference between bearer bonds and tequila.
If you restart heist after this 72 hours, order is the same as before nerf - panther/pink diamond > bearer bonds > ruby necklace > tequila, because bonus on secondary targets is not applied.

**Comment by Your-Paramour** [comment]
So is the 72 hour bonus from the time you launch the heist finale or from when you pay the setup fee for the heist? Lets say you pay the setup fee in time to get hard mode activate, you do all the setups but you wait a week of real time (and over 3 in game days), would the 72hr bonus still be active?

**Comment by MichalD96** [comment]
Yes, it will be active.
72 hours timer starts 48 minutes after you completed heist with friend(s) or 3 hours after you completed heist solo, and counts until you pay for the next heist. You just need to pay, don't even need to scope the island. It will be active even if you come back to the game a month later (the same as hard mode)

**Comment by MichalD96** [comment]
This video is outdated, but explains general concept of that bonus.
https://www.youtube.com/watch?v=7JL3FOdVCsI

After the recent nerfs, the best is to play on hard mode from two reasons
  - $100k elite challenge bonus
  - tequila is second the best target, because of the 72 hours bonus, and you have 60% change go get it.
Waiting 72 hours guarantee you better primary target, but you lose that bonuses that are usually worth more (except the heist with pink diamond).
I made calculations on random scenarios in standard and hard mode, and in 85% of scenarios playing on hard mode is more profitable, no matter the conditions on the island. Hard mode and 72 hours bonus gives way more money in long period of time. And of course playing for example one heist every day you will earn more than waiting 3 days and hoping for the diamond.
