### ISSUE TITLE
need an update

### ISSUE THREAD

**Issue by ENL987465** [MichalD96/Perico-heist-goods-counter#20]
The cash box in the office on the second floor has become a nerf and the revenue calculated is incorrect.  Please update it.

I used a translator. Please understand if the grammar is not correct.

**Comment by MichalD96** [comment]
What nerf you mean?
As far as I know safe value may be between $20k - $99k, and that is exactly calculator value

**Comment by ENL987465** [comment]
The 'minimum amount of safe' posted on the website is not that amount.
Please refer to the attached picture.

**Comment by ENL987465** [comment]
The 'minimum amount of safe' posted on the website is not that amount.
I would appreciate it if you could refer to the attached picture.


![123132](https://github.com/user-attachments/assets/1f63d5e9-a483-4fdd-914a-a572ad85261e)

**Comment by MichalD96** [comment]
It is the average value and not really significant comparing to the final value.
`($20000 + $99000) / 2 = $59500`
From my experience rarely you get close to $20k or $99k.
Statistically average value is the most correct.
